---
- name: Add Nginx Repository Key
  apt_key:
    url: "{{ nginx_signing_key }}"
    state: present

- name: Add Nginx Repository
  apt_repository:
    repo: "{{ nginx_repository }}"
    state: present

- name: Add Nginx Repository (Source)
  apt_repository:
   repo: "{{ nginx_repository_src }}"
   state: present

- name: Install nginx
  package:
    name: nginx
    state: latest
    update_cache: yes
  notify: Start nginx