---
- name: Accept new incoming HTTP connections.
  iptables:
    chain: INPUT
    protocol: tcp
    destination_port: 80
    ctstate: NEW
    syn: match
    jump: ACCEPT
    comment: Accept new incoming HTTP connections.

- name: Accept new incoming HTTPS connections. 
  iptables:
    chain: INPUT
    protocol: tcp
    destination_port: 443
    ctstate: NEW
    syn: match
    jump: ACCEPT
    comment: Accept new incoming HTTPS connections.