---
- import_tasks: installation.yml
- import_tasks: certificate.yml

- name: Copy default.conf to server
  copy:
    src: files/default.conf
    dest: /etc/nginx/conf.d/default.conf
    owner: root
    group: root
    mode: 0644
  notify: Restart nginx