---
- name: Add Nginx Repository Key
  apt_key:
    url: http://nginx.org/keys/nginx_signing.key
    state: present
- name: Add Nginx Repository
  apt_repository:
    repo: deb http://nginx.org/packages/debian/ stretch nginx
    state: present
- name: Add Nginx Repository (Source)
  apt_repository:
   repo: deb-src http://nginx.org/packages/debian/ stretch nginx
   state: present
- name: Install nginx
  package:
    name: nginx
    state: latest
    update_cache: yes
