---
- import_tasks: installation.yml
- import_tasks: certificate.yml
- import_tasks: iptables_accept_incoming_https.yml

- name: Copy errorpages to server
  copy:
    src: files/error
    dest: /srv/
    owner: root
    group: root
    mode: 0755

- name: Copy nginx configuration files 
  copy:
    src: "{{ nginx_configuration_source }}"
    dest: "{{ nginx_configuration_destination }}"
    owner: root
    group: root
    mode: 0644
  notify: Reload nginx
